[package]
name = "ells-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
base64.workspace = true
cbc = "0.1"
chacha20poly1305.workspace = true
chrono = "0.4"
des = "0.8"
dirs.workspace = true
futures.workspace = true
md-5 = "0.11.0"
rand.workspace = true
russh.workspace = true
russh-sftp.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
zeroize.workspace = true

[dev-dependencies]
ells-transfer.workspace = true
tempfile = "3"
